export const allProducts = [
    {
        "productId": "01",
        "productCategory": "apparel",
        "subCategory": "hoodies",
        "special": "New Arrival",
        "price": "50",
        "imgPath": "/img/men-hoodie-1.jpg",
        "title": "Classic Hoodie",
        "description": "Comfortable hoodie for everyday wear.",
        "stylesCount": "2",
        "sizes": "S, M, L, XL",
        "brand": "CoolWear",
        "color": "Blue",
        "tags": "Casual, Cozy, Men, Women"
    },
    {
        "productId": "02",
        "productCategory": "apparel",
        "subCategory": "tops&t-shirts",
        "special": "Best Seller",
        "price": "40",
        "imgPath": "/img/men-tshirt-1.jpg",
        "title": "Basic T-Shirt",
        "description": "Soft cotton t-shirt perfect for layering.",
        "stylesCount": "3",
        "sizes": "M, L, XL",
        "brand": "UrbanFit",
        "color": "White",
        "tags": "Classic, Simple, Men, Women"
    },
    {
        "productId": "03",
        "productCategory": "apparel",
        "subCategory": "pants&bottoms",
        "special": "Limited Edition",
        "price": "75",
        "imgPath": "/img/men-pants-1.jpg",
        "title": "Denim Jeans",
        "description": "Durable jeans with a modern fit.",
        "stylesCount": "1",
        "sizes": "30, 32, 34, 36",
        "brand": "DenimPro",
        "color": "Indigo",
        "tags": "Casual, Durable, Men"
    },
    {
        "productId": "04",
        "productCategory": "apparel",
        "subCategory": "accessories",
        "special": "New Arrival",
        "price": "30",
        "imgPath": "/img/men-accessory-1.jpg",
        "title": "Leather Belt",
        "description": "Stylish leather belt with a classic buckle.",
        "stylesCount": "0",
        "sizes": "One Size",
        "brand": "BeltCo",
        "color": "Brown",
        "tags": "Accessory, Leather, Men"
    },
    {
        "productId": "05",
        "productCategory": "apparel",
        "subCategory": "hoodies",
        "special": "Best Seller",
        "price": "55",
        "imgPath": "/img/women-hoodie-1.jpg",
        "title": "Women's Fleece Hoodie",
        "description": "Warm fleece hoodie for colder days.",
        "stylesCount": "2",
        "sizes": "XS, S, M, L",
        "brand": "SoftWear",
        "color": "Grey",
        "tags": "Casual, Warm, Women"
    },
    {
        "productId": "06",
        "productCategory": "apparel",
        "subCategory": "tops&t-shirts",
        "special": "Limited Edition",
        "price": "25",
        "imgPath": "/img/women-top-1.jpg",
        "title": "Graphic T-Shirt",
        "description": "Lightweight shirt with a unique graphic.",
        "stylesCount": "3",
        "sizes": "S, M, L",
        "brand": "ArtWear",
        "color": "Black",
        "tags": "Graphic, Stylish"
    },
    {
        "productId": "07",
        "productCategory": "apparel",
        "subCategory": "pants&bottoms",
        "special": "New Arrival",
        "price": "65",
        "imgPath": "/img/women-pants-1.jpg",
        "title": "Stretch Leggings",
        "description": "Comfortable leggings for all-day wear.",
        "stylesCount": "2",
        "sizes": "XS, S, M, L, XL",
        "brand": "ActiveWear",
        "color": "Navy",
        "tags": "Active, Comfortable, Women"
    },
    {
        "productId": "08",
        "productCategory": "apparel",
        "subCategory": "accessories",
        "special": "On Sale",
        "price": "20",
        "imgPath": "/img/women-accessory-1.jpg",
        "title": "Knitted Scarf",
        "description": "Cozy scarf to keep you warm.",
        "stylesCount": "1",
        "sizes": "One Size",
        "brand": "WarmNest",
        "color": "Red",
        "tags": "Accessory, Winter, Women, Men, Sale"
    },
    {
        "productId": "09",
        "productCategory": "gear",
        "subCategory": "completes",
        "special": "Best Seller",
        "price": "120",
        "imgPath": "/img/gear-complete-1.jpg",
        "title": "Beginner Complete Skateboard",
        "description": "Complete skateboard perfect for beginners.",
        "stylesCount": "1",
        "sizes": "8.0",
        "brand": "SkatePro",
        "color": "Black",
        "tags": "Beginner, Durable"
    },
    {
        "productId": "10",
        "productCategory": "gear",
        "subCategory": "completes",
        "special": "New Arrival",
        "price": "150",
        "imgPath": "/img/gear-complete-2.jpg",
        "title": "Pro Complete Board",
        "description": "Professional-grade skateboard for experts.",
        "stylesCount": "2",
        "sizes": "8.5",
        "brand": "ProSkate",
        "color": "Natural",
        "tags": "Pro, High-Quality"
    },
    {
        "productId": "11",
        "productCategory": "gear",
        "subCategory": "boards",
        "special": "New Arrival",
        "price": "100",
        "imgPath": "/img/gear-board-1.jpg",
        "title": "Siiick Pro Deck",
        "description": "A super siiick board for amateurs and aspiring pros.",
        "stylesCount": "0",
        "sizes": "8.2",
        "brand": "So Siiick",
        "color": "White",
        "tags": "Pro"
    },
    {
        "productId": "12",
        "productCategory": "gear",
        "subCategory": "boards",
        "special": "Limited Edition",
        "price": "95",
        "imgPath": "/img/gear-board-2.jpg",
        "title": "Signature Deck",
        "description": "Deck designed for advanced tricks and durability.",
        "stylesCount": "1",
        "sizes": "8.0, 8.5",
        "brand": "SignatureSkate",
        "color": "Red",
        "tags": "Advanced, Durable"
    },
    {
        "productId": "13",
        "productCategory": "gear",
        "subCategory": "wheels",
        "special": "On Sale",
        "price": "35",
        "imgPath": "/img/gear-wheels-1.jpg",
        "title": "All-Terrain Wheels",
        "description": "Durable wheels for all surfaces.",
        "stylesCount": "3",
        "sizes": "52mm, 54mm",
        "brand": "WheelWorks",
        "color": "Blue",
        "tags": "Durable, Versatile, Sale"
    },
    {
        "productId": "14",
        "productCategory": "gear",
        "subCategory": "wheels",
        "special": "Best Seller",
        "price": "40",
        "imgPath": "/img/gear-wheels-2.jpg",
        "title": "Street Wheels",
        "description": "Wheels designed for street skating.",
        "stylesCount": "2",
        "sizes": "52mm, 54mm",
        "brand": "StreetGlide",
        "color": "White",
        "tags": "Street, Smooth"
    },
    {
        "productId": "15",
        "productCategory": "gear",
        "subCategory": "trucks",
        "special": "New Arrival",
        "price": "60",
        "imgPath": "/img/gear-trucks-1.jpg",
        "title": "Low Trucks",
        "description": "Low-profile trucks for optimal control.",
        "stylesCount": "1",
        "sizes": "139mm",
        "brand": "TruckMaster",
        "color": "Silver",
        "tags": "Control, Durable"
    },
    {
        "productId": "16",
        "productCategory": "gear",
        "subCategory": "trucks",
        "special": "Limited Edition",
        "price": "65",
        "imgPath": "/img/gear-trucks-2.jpg",
        "title": "Pro Series Trucks",
        "description": "Trucks built for professional use.",
        "stylesCount": "2",
        "sizes": "149mm",
        "brand": "ProTrucks",
        "color": "Black",
        "tags": "Pro, High-Quality"
    },
    {
        "productId": "17",
        "productCategory": "gear",
        "subCategory": "helmets&pads",
        "special": "On Sale",
        "price": "45",
        "imgPath": "/img/gear-helmet-1.jpg",
        "title": "Basic Helmet",
        "description": "Helmet for protection during rides.",
        "stylesCount": "3",
        "sizes": "S, M, L",
        "brand": "SafetyFirst",
        "color": "Black",
        "tags": "Protection, Basic, Sale"
    },
    {
        "productId": "18",
        "productCategory": "gear",
        "subCategory": "helmets&pads",
        "special": "New Arrival",
        "price": "60",
        "imgPath": "/img/gear-helmet-2.jpg",
        "title": "Pro Helmet",
        "description": "Lightweight and protective helmet for pros.",
        "stylesCount": "2",
        "sizes": "M, L",
        "brand": "ProSafety",
        "color": "Blue",
        "tags": "Pro, Lightweight"
    },

    {
        "productId": "19",
        "productCategory": "gear",
        "subCategory": "completes",
        "special": "Limited Edition",
        "price": "175",
        "imgPath": "/img/gear-complete-3.jpg",
        "title": "Custom Graphic Complete",
        "description": "Complete skateboard with custom artwork.",
        "stylesCount": "1",
        "sizes": "8.25",
        "brand": "ArtSkate",
        "color": "Multi",
        "tags": "Custom, Artistic"
    },
    {
        "productId": "20",
        "productCategory": "gear",
        "subCategory": "boards",
        "special": "New Arrival",
        "price": "110",
        "imgPath": "/img/gear-board-3.jpg",
        "title": "Carbon Fiber Deck",
        "description": "Lightweight and durable carbon fiber deck.",
        "stylesCount": "0",
        "sizes": "8.5",
        "brand": "CarbonX",
        "color": "Black",
        "tags": "Lightweight, Durable"
    },
    {
        "productId": "21",
        "productCategory": "gear",
        "subCategory": "wheels",
        "special": "On Sale",
        "price": "30",
        "imgPath": "/img/gear-wheels-3.jpg",
        "title": "LED Light Wheels",
        "description": "Wheels that light up while you skate.",
        "stylesCount": "1",
        "sizes": "54mm",
        "brand": "NightSkate",
        "color": "Multi",
        "tags": "Light-Up, Fun, Sale"
    },
    {
        "productId": "22",
        "productCategory": "gear",
        "subCategory": "trucks",
        "special": "Best Seller",
        "price": "55",
        "imgPath": "/img/gear-trucks-3.jpg",
        "title": "Mid-Profile Trucks",
        "description": "Balanced trucks for versatile skating.",
        "stylesCount": "2",
        "sizes": "139mm",
        "brand": "BalancePro",
        "color": "Silver",
        "tags": "Versatile, Balanced"
    },
    {
        "productId": "23",
        "productCategory": "gear",
        "subCategory": "helmets&pads",
        "special": "Best Seller",
        "price": "65",
        "imgPath": "/img/gear-padset-1.jpg",
        "title": "Complete Pad Set",
        "description": "Knee, elbow, and wrist pads for full protection.",
        "stylesCount": "3",
        "sizes": "S, M, L",
        "brand": "SafeGear",
        "color": "Black",
        "tags": "Protection, Full Set"
    },
    {
        "productId": "24",
        "productCategory": "apparel",
        "subCategory": "kids",
        "special": "New Arrival",
        "price": "25",
        "imgPath": "/img/kids-tee-1.jpg",
        "title": "Kids' Graphic Tee",
        "description": "Fun t-shirt with a cool graphic print.",
        "stylesCount": "2",
        "sizes": "XS, S, M",
        "brand": "KiddoWear",
        "color": "Yellow",
        "tags": "Casual, Fun"
    },
    {
        "productId": "25",
        "productCategory": "apparel",
        "subCategory": "kids",
        "special": "On Sale",
        "price": "30",
        "imgPath": "/img/kids-hoodie-1.jpg",
        "title": "Kids' Hoodie",
        "description": "Soft hoodie perfect for cooler weather.",
        "stylesCount": "1",
        "sizes": "S, M, L",
        "brand": "TinyThreads",
        "color": "Green",
        "tags": "Casual, Cozy, Sale"
    },
    {
        "productId": "26",
        "productCategory": "apparel",
        "subCategory": "tops&t-shirts",
        "special": "New Arrival",
        "price": "90",
        "imgPath": "/img/men-jacket-1.jpg",
        "title": "Winter Jacket",
        "description": "Warm and waterproof jacket for winter.",
        "stylesCount": "3",
        "sizes": "M, L, XL",
        "brand": "ArcticWear",
        "color": "Navy",
        "tags": "Winter, Waterproof, Men"
    },
    {
        "productId": "27",
        "productCategory": "apparel",
        "subCategory": "tops&t-shirts",
        "special": "Limited Edition",
        "price": "35",
        "imgPath": "/img/women-top-2.jpg",
        "title": "Floral Blouse",
        "description": "Elegant blouse with floral design.",
        "stylesCount": "2",
        "sizes": "S, M, L",
        "brand": "BloomingStyle",
        "color": "White",
        "tags": "Elegant, Floral, Women"
    },
    {
        "productId": "28",
        "productCategory": "gear",
        "subCategory": "completes",
        "special": "New Arrival",
        "price": "160",
        "imgPath": "/img/gear-complete-4.jpg",
        "title": "Retro Complete Board",
        "description": "Complete skateboard with a vintage design.",
        "stylesCount": "1",
        "sizes": "8.0",
        "brand": "RetroRide",
        "color": "Yellow",
        "tags": "Vintage, Stylish"
    },
    {
        "productId": "29",
        "productCategory": "apparel",
        "subCategory": "shoes",
        "special": "Best Seller",
        "price": "120",
        "imgPath": "/img/apparel-shoes-1.jpg",
        "title": "Classic Skate Shoes",
        "description": "Durable skate shoes with reinforced soles.",
        "stylesCount": "3",
        "sizes": "8, 9, 10, 11",
        "brand": "SkateMaster",
        "color": "Black",
        "tags": "Durable, Classic"
    },
    {
        "productId": "30",
        "productCategory": "apparel",
        "subCategory": "hoodies",
        "special": "New Arrival",
        "price": "60",
        "imgPath": "/img/apparel-hoodie-2.jpg",
        "title": "Oversized Hoodie",
        "description": "Soft and comfortable hoodie, perfect for layering.",
        "stylesCount": "2",
        "sizes": "M, L, XL",
        "brand": "ComfyWear",
        "color": "Grey",
        "tags": "Cozy, Casual"
    },
    {
        "productId": "31",
        "productCategory": "apparel",
        "subCategory": "tops&t-shirts",
        "special": "Limited Edition",
        "price": "35",
        "imgPath": "/img/apparel-tshirt-2.jpg",
        "title": "Vintage Logo Tee",
        "description": "Retro-inspired t-shirt with vintage logo print.",
        "stylesCount": "1",
        "sizes": "S, M, L, XL",
        "brand": "RetroThreads",
        "color": "White",
        "tags": "Vintage, Retro"
    },
    {
        "productId": "32",
        "productCategory": "apparel",
        "subCategory": "pants&bottoms",
        "special": "On Sale",
        "price": "50",
        "imgPath": "/img/apparel-pants-2.jpg",
        "title": "Slim Fit Jeans",
        "description": "Stylish jeans with a comfortable slim fit.",
        "stylesCount": "1",
        "sizes": "S, M, L, XL",
        "brand": "UrbanFit",
        "color": "Blue",
        "tags": "Slim, Comfortable, Sale"
    },
    {
        "productId": "33",
        "productCategory": "gear",
        "subCategory": "hardware",
        "special": "New Arrival",
        "price": "10",
        "imgPath": "/img/gear-hardware-1.jpg",
        "title": "Pro Hardware Set",
        "description": "Complete set of nuts and bolts for your skateboard.",
        "stylesCount": "0",
        "sizes": "Standard",
        "brand": "BoltUp",
        "color": "Metal",
        "tags": "Durable, Essential"
    },
    {
        "productId": "34",
        "productCategory": "gear",
        "subCategory": "trucks",
        "special": "Limited Edition",
        "price": "70",
        "imgPath": "/img/gear-trucks-4.jpg",
        "title": "Ultra-Light Trucks",
        "description": "High-performance, lightweight trucks.",
        "stylesCount": "1",
        "sizes": "149mm",
        "brand": "LightRide",
        "color": "Silver",
        "tags": "Lightweight, Performance"
    },
    {
        "productId": "35",
        "productCategory": "gear",
        "subCategory": "wheels",
        "special": "Best Seller",
        "price": "45",
        "imgPath": "/img/gear-wheels-4.jpg",
        "title": "All-Terrain Wheels",
        "description": "Rugged wheels for any surface.",
        "stylesCount": "1",
        "sizes": "58mm",
        "brand": "GripMaster",
        "color": "Black",
        "tags": "Rugged, Durable"
    },
    {
        "productId": "36",
        "productCategory": "gear",
        "subCategory": "completes",
        "special": "On Sale",
        "price": "150",
        "imgPath": "/img/gear-complete-5.jpg",
        "title": "All-Rounder Complete Board",
        "description": "Versatile skateboard complete for all skill levels.",
        "stylesCount": "2",
        "sizes": "8.0",
        "brand": "FlexRide",
        "color": "Green",
        "tags": "Versatile, Beginner-Friendly, Sale"
    },
    {
        "productId": "37",
        "productCategory": "apparel",
        "subCategory": "accessories",
        "special": "New Arrival",
        "price": "15",
        "imgPath": "/img/apparel-accessory-1.jpg",
        "title": "Skater Socks",
        "description": "High-quality socks with a skater style.",
        "stylesCount": "3",
        "sizes": "One Size",
        "brand": "SockIt",
        "color": "White",
        "tags": "Comfort, Style"
    },
    {
        "productId": "38",
        "productCategory": "gear",
        "subCategory": "boards",
        "special": "Limited Edition",
        "price": "130",
        "imgPath": "/img/gear-board-4.jpg",
        "title": "Limited Edition Bamboo Deck",
        "description": "Eco-friendly bamboo deck with unique graphic.",
        "stylesCount": "0",
        "sizes": "8.25",
        "brand": "EcoSkate",
        "color": "Natural",
        "tags": "Eco-Friendly, Unique"
    },
    {
        "productId": "39",
        "productCategory": "apparel",
        "subCategory": "tops&t-shirts",
        "special": "Exclusive",
        "price": "25",
        "imgPath": "/img/apparel-tshirt-3.jpg",
        "title": "Graphic Tee - Sunset Edition",
        "description": "Soft cotton tee with a vibrant sunset print.",
        "stylesCount": "1",
        "sizes": "S, M, L",
        "brand": "VistaVibe",
        "color": "Orange",
        "tags": "Casual, Vibrant"
    },
    {
        "productId": "40",
        "productCategory": "apparel",
        "subCategory": "hoodies",
        "special": "On Sale",
        "price": "55",
        "imgPath": "/img/apparel-hoodie-3.jpg",
        "title": "Eco-Fleece Hoodie",
        "description": "Warm and eco-friendly hoodie made from recycled fibers.",
        "stylesCount": "2",
        "sizes": "M, L, XL",
        "brand": "GreenWear",
        "color": "Forest Green",
        "tags": "Eco-Friendly, Warm, Sale"
    },
    {
        "productId": "41",
        "productCategory": "apparel",
        "subCategory": "pants&bottoms",
        "special": "Best Seller",
        "price": "45",
        "imgPath": "/img/apparel-pants-3.jpg",
        "title": "Cargo Joggers",
        "description": "Functional joggers with multiple pockets, great for on-the-go.",
        "stylesCount": "3",
        "sizes": "M, L, XL",
        "brand": "StreetFlex",
        "color": "Olive",
        "tags": "Functional, Comfortable"
    },
    {
        "productId": "42",
        "productCategory": "gear",
        "subCategory": "helmets&pads",
        "special": "New Arrival",
        "price": "80",
        "imgPath": "/img/gear-helmet-1.jpg",
        "title": "Impact-Pro Helmet",
        "description": "High-impact helmet designed for extreme skateboarding.",
        "stylesCount": "1",
        "sizes": "M, L",
        "brand": "SafeSkate",
        "color": "Matte Black",
        "tags": "Safety, Durable"
    },
    {
        "productId": "43",
        "productCategory": "gear",
        "subCategory": "wheels",
        "special": "Limited Edition",
        "price": "60",
        "imgPath": "/img/gear-wheels-5.jpg",
        "title": "Neon Glide Wheels",
        "description": "High-rebound neon wheels for smooth rides and style.",
        "stylesCount": "2",
        "sizes": "54mm",
        "brand": "GlowRider",
        "color": "Neon Green",
        "tags": "Smooth, Stylish"
    },
    {
        "productId": "44",
        "productCategory": "gear",
        "subCategory": "hardware",
        "special": "Exclusive",
        "price": "15",
        "imgPath": "/img/gear-hardware-2.jpg",
        "title": "Titanium Bolt Set",
        "description": "Lightweight titanium bolts for secure assembly.",
        "stylesCount": "0",
        "sizes": "Standard",
        "brand": "BoltMaster",
        "color": "Metallic Grey",
        "tags": "Lightweight, Durable"
    },
    {
        "productId": "45",
        "productCategory": "apparel",
        "subCategory": "shoes",
        "special": "Best Seller",
        "price": "110",
        "imgPath": "/img/apparel-shoes-2.jpg",
        "title": "High-Top Skater Shoes",
        "description": "Supportive high-tops with reinforced toes for added durability.",
        "stylesCount": "2",
        "sizes": "8, 9, 10, 11, 12",
        "brand": "KickIt",
        "color": "Red and Black",
        "tags": "Supportive, Durable"
    },
    {
        "productId": "46",
        "productCategory": "gear",
        "subCategory": "completes",
        "special": "New Arrival",
        "price": "165",
        "imgPath": "/img/gear-complete-6.jpg",
        "title": "Urban Cruiser Complete",
        "description": "Perfect board for commuting with a smooth and sturdy setup.",
        "stylesCount": "1",
        "sizes": "8.5",
        "brand": "SmoothGlide",
        "color": "Teal",
        "tags": "Smooth, Sturdy"
    },
    {
        "productId": "47",
        "productCategory": "apparel",
        "subCategory": "accessories",
        "special": "Limited Edition",
        "price": "20",
        "imgPath": "/img/apparel-accessory-2.jpg",
        "title": "Embroidered Snapback Cap",
        "description": "Stylish snapback cap with embroidered logo.",
        "stylesCount": "1",
        "sizes": "One Size",
        "brand": "HeadGear",
        "color": "Black",
        "tags": "Stylish, Adjustable"
    },
    {
        "productId": "48",
        "productCategory": "gear",
        "subCategory": "trucks",
        "special": "On Sale",
        "price": "65",
        "imgPath": "/img/gear-trucks-5.jpg",
        "title": "All-Terrain Trucks",
        "description": "Durable trucks built for all surfaces, smooth and tough.",
        "stylesCount": "2",
        "sizes": "139mm",
        "brand": "TerrainTough",
        "color": "Gunmetal",
        "tags": "Durable, All-Terrain, Sale"
    },
    {
        "productId": "49",
        "productCategory": "apparel",
        "subCategory": "tops&t-shirts",
        "special": "New Arrival",
        "price": "22",
        "imgPath": "/img/apparel-tshirt-4.jpg",
        "title": "Classic Logo Tee",
        "description": "Simple and stylish tee featuring our classic logo.",
        "stylesCount": "1",
        "sizes": "S, M, L, XL",
        "brand": "PrimeStyle",
        "color": "Navy Blue",
        "tags": "Casual, Comfortable"
    },
    {
        "productId": "50",
        "productCategory": "apparel",
        "subCategory": "pants&bottoms",
        "special": "Exclusive",
        "price": "48",
        "imgPath": "/img/apparel-pants-4.jpg",
        "title": "Slim Fit Chinos",
        "description": "Stylish slim-fit chinos perfect for everyday wear.",
        "stylesCount": "2",
        "sizes": "S, M, L, XL",
        "brand": "ModernThreads",
        "color": "Khaki",
        "tags": "Stylish, Comfortable"
    },
    {
        "productId": "51",
        "productCategory": "gear",
        "subCategory": "helmets&pads",
        "special": "Limited Edition",
        "price": "90",
        "imgPath": "/img/gear-helmet-2.jpg",
        "title": "Rider’s Choice Helmet",
        "description": "A stylish helmet with reinforced protection for skaters.",
        "stylesCount": "1",
        "sizes": "M, L",
        "brand": "TopShield",
        "color": "Glossy Blue",
        "tags": "Protection, Durable"
    },
    {
        "productId": "52",
        "productCategory": "apparel",
        "subCategory": "accessories",
        "special": "On Sale",
        "price": "18",
        "imgPath": "/img/apparel-accessory-3.jpg",
        "title": "Leather Wristband",
        "description": "Handcrafted leather wristband for a rugged look.",
        "stylesCount": "1",
        "sizes": "One Size",
        "brand": "BoldWear",
        "color": "Dark Brown",
        "tags": "Handcrafted, Stylish, Sale"
    },
    {
        "productId": "53",
        "productCategory": "gear",
        "subCategory": "wheels",
        "special": "Best Seller",
        "price": "58",
        "imgPath": "/img/gear-wheels-6.jpg",
        "title": "Speedster Wheels",
        "description": "High-performance wheels for fast, smooth rides.",
        "stylesCount": "2",
        "sizes": "52mm",
        "brand": "SwiftSkate",
        "color": "Red",
        "tags": "Fast, Smooth"
    },
    {
        "productId": "54",
        "productCategory": "apparel",
        "subCategory": "shoes",
        "special": "Limited Edition",
        "price": "115",
        "imgPath": "/img/apparel-shoes-3.jpg",
        "title": "Canvas Slip-Ons",
        "description": "Lightweight canvas slip-ons for easy everyday wear.",
        "stylesCount": "1",
        "sizes": "7, 8, 9, 10, 11",
        "brand": "UrbanStep",
        "color": "Charcoal",
        "tags": "Comfortable, Casual"
    },
    {
        "productId": "55",
        "productCategory": "gear",
        "subCategory": "boards",
        "special": "New Arrival",
        "price": "140",
        "imgPath": "/img/gear-board-6.jpg",
        "title": "Shredder Skate Deck",
        "description": "Durable deck built to withstand the toughest tricks.",
        "stylesCount": "1",
        "sizes": "8.5",
        "brand": "ShredMaster",
        "color": "Black&White",
        "tags": "Durable, Reliable"
    },
    {
        "productId": "56",
        "productCategory": "gear",
        "subCategory": "trucks",
        "special": "Exclusive",
        "price": "70",
        "imgPath": "/img/gear-trucks-6.jpg",
        "title": "Heavy-Duty Trucks",
        "description": "Built tough for serious riders who need durability.",
        "stylesCount": "1",
        "sizes": "144mm",
        "brand": "EnduroTrucks",
        "color": "Steel",
        "tags": "Durable, Reliable"
    },
    {
        "productId": "57",
        "productCategory": "apparel",
        "subCategory": "hoodies",
        "special": "New Arrival",
        "price": "65",
        "imgPath": "/img/apparel-hoodie-4.jpg",
        "title": "Zip-Up Hoodie",
        "description": "Casual zip-up hoodie perfect for layering.",
        "stylesCount": "2",
        "sizes": "S, M, L, XL",
        "brand": "ChillWear",
        "color": "Heather Gray",
        "tags": "Casual, Comfortable"
    },
    {
        "productId": "58",
        "productCategory": "apparel",
        "subCategory": "tops&t-shirts",
        "special": "Best Seller",
        "price": "30",
        "imgPath": "/img/apparel-tshirt-5.jpg",
        "title": "Vintage Graphic Tee",
        "description": "Retro graphic tee with a vintage look and feel.",
        "stylesCount": "1",
        "sizes": "S, M, L, XL",
        "brand": "ThrowbackThreads",
        "color": "Washed Blue",
        "tags": "Retro, Comfortable"
    },
    {
        "productId": "59",
        "productCategory": "gear",
        "subCategory": "hardware",
        "special": "On Sale",
        "price": "12",
        "imgPath": "/img/gear-hardware-3.jpg",
        "title": "Precision Bearing Set",
        "description": "Smooth and fast bearings for optimal performance.",
        "stylesCount": "0",
        "sizes": "Standard",
        "brand": "SpeedPro",
        "color": "Silver",
        "tags": "Smooth, Fast, Sale"
    },
    {
        "productId": "60",
        "productCategory": "gear",
        "subCategory": "completes",
        "special": "New Arrival",
        "price": "170",
        "imgPath": "/img/gear-complete-7.jpg",
        "title": "All-Terrain Complete Board",
        "description": "Designed for off-road skateboarding on any surface.",
        "stylesCount": "1",
        "sizes": "9.0",
        "brand": "RoughRide",
        "color": "Camouflage",
        "tags": "All-Terrain, Sturdy"
    }
]

function filterProductsByKey(array, key, value, tags = false) {
    if(tags)
    {
        return array.filter(item => item[key].includes(value));
    }
    else{
        return array.filter(item => item[key] === value);
    }
}


export const apparelProducts = filterProductsByKey(allProducts, "productCategory", "apparel");
export const menProducts = filterProductsByKey(allProducts, "tags", "Men", true);
export const womenProducts = filterProductsByKey(allProducts, "tags", "Women", true);
export const saleProducts = filterProductsByKey(allProducts, "tags", "Sale", true);
export const gearProducts = filterProductsByKey(allProducts, "productCategory", "gear");
export const wheelsProducts = filterProductsByKey(allProducts, "subCategory", "wheels");
export const boardsProducts = filterProductsByKey(allProducts, "subCategory", "boards");
export const safetyProducts = filterProductsByKey(allProducts, "subCategory", "helmets&pads");
export const hardwareProducts = filterProductsByKey(allProducts, "subCategory", "hardware");
export const trucksProducts = filterProductsByKey(allProducts, "subCategory", "trucks");
export const completesProducts = filterProductsByKey(allProducts, "subCategory", "completes");
export const shoeProducts = filterProductsByKey(allProducts, "subCategory", "shoes");
export const accessoriesProducts = filterProductsByKey(allProducts, "subCategory", "accessories");
export const topsAndTshirtProducts = filterProductsByKey(allProducts, "subCategory", "tops&t-shirts");
export const pantsAndBottomsProducts = filterProductsByKey(allProducts, "subCategory", "pants&bottoms");
export const hoodiesProducts = filterProductsByKey(allProducts, "subCategory", "hoodies");