export const stateList = [
    { stateId: "AL", val: "Alabama" },
    { stateId: "AK", val: "Alaska" },
    { stateId: "AZ", val: "Arizona" },
    { stateId: "AR", val: "Arkansas" },
    { stateId: "CA", val: "California" },
    { stateId: "CO", val: "Colorado" },
    { stateId: "CT", val: "Connecticut" },
    { stateId: "DE", val: "Delaware" },
    { stateId: "FL", val: "Florida" },
    { stateId: "GA", val: "Georgia" },
    { stateId: "HI", val: "Hawaii" },
    { stateId: "ID", val: "Idaho" },
    { stateId: "IL", val: "Illinois" },
    { stateId: "IN", val: "Indiana" },
    { stateId: "IA", val: "Iowa" },
    { stateId: "KS", val: "Kansas" },
    { stateId: "KY", val: "Kentucky" },
    { stateId: "LA", val: "Louisiana" },
    { stateId: "ME", val: "Maine" },
    { stateId: "MD", val: "Maryland" },
    { stateId: "MA", val: "Massachusetts" },
    { stateId: "MI", val: "Michigan" },
    { stateId: "MN", val: "Minnesota" },
    { stateId: "MS", val: "Mississippi" },
    { stateId: "MO", val: "Missouri" },
    { stateId: "MT", val: "Montana" },
    { stateId: "NE", val: "Nebraska" },
    { stateId: "NV", val: "Nevada" },
    { stateId: "NH", val: "New Hampshire" },
    { stateId: "NJ", val: "New Jersey" },
    { stateId: "NM", val: "New Mexico" },
    { stateId: "NY", val: "New York" },
    { stateId: "NC", val: "North Carolina" },
    { stateId: "ND", val: "North Dakota" },
    { stateId: "OH", val: "Ohio" },
    { stateId: "OK", val: "Oklahoma" },
    { stateId: "OR", val: "Oregon" },
    { stateId: "PA", val: "Pennsylvania" },
    { stateId: "RI", val: "Rhode Island" },
    { stateId: "SC", val: "South Carolina" },
    { stateId: "SD", val: "South Dakota" },
    { stateId: "TN", val: "Tennessee" },
    { stateId: "TX", val: "Texas" },
    { stateId: "UT", val: "Utah" },
    { stateId: "VT", val: "Vermont" },
    { stateId: "VA", val: "Virginia" },
    { stateId: "WA", val: "Washington" },
    { stateId: "WV", val: "West Virginia" },
    { stateId: "WI", val: "Wisconsin" },
    { stateId: "WY", val: "Wyoming" }
]
